# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: O blog do Pylonnnn
email: pylonbr@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Este é o blog do Pylon. vc está muito perdido se caiu aqui.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://thepylon.github.io/" # the base hostname & protocol for your site
twitter_username: pylon
github_username:  pylon

# Build settings
markdown: kramdown
